### ISSUE TITLE
Pan gesture disables the scrolling in a tableview

### ISSUE THREAD

**Issue by KyleGreenlaw** [ECSlidingViewController/ECSlidingViewController#129]

**Comment by rawanOmari** [comment]
@airdrummingfool  hi :) 
thanks for your answer. i faced the same problem that you've talked about it. 
i have menu side, and i used panGesture to slide it  in - out 
and i have tableview, so the swipe to delete is disable by the pan. 
i saw your answer, but i didn't know how to make the direction of swipGesture opposite PanGesture
so i'll be so thankful for any help :)

**Comment by airdrummingfool** [comment]
@rawanOmari: to set the swipe gesture recognizer's direction left (since my pan GR was to the right), I had to loop through all of the gesture recognizers on the tableview and find the swipe GR, then modify it. Note that this isn't necessary for iOS 7 or 8 (I think... this code is old) since newer tableviews use a pan gesture recognizer to delete.

``` objc
	/*
	 * Set swipe to delete to only work in one direction, and make sure
	 *	swipe to delete fails before triggering the pan gr.
	 * NOTE: This doesn't affect iOS 7+ (iOS 7+ tableView uses a panGR,
	 *	not swipeGR for editing)
	 */
	NSLog(@"Configuring swipe-to-delete GR");
	for (UIGestureRecognizer *existingGR in self.tableView.gestureRecognizers) {
		if ([existingGR isKindOfClass:[UISwipeGestureRecognizer class]]) {
			NSLog(@"Found swipe-to-delete GR: %@", existingGR);
			[(UISwipeGestureRecognizer *)existingGR setDirection:UISwipeGestureRecognizerDirectionLeft];
			[self.slidingViewController.panGesture requireGestureRecognizerToFail:existingGR];
			break;
		}
	}
```
