### ISSUE TITLE
-slidingViewController returns nil during unit tests

### ISSUE THREAD

**Issue by s73v3r** [ECSlidingViewController/ECSlidingViewController#269]
I installed ECSlidingViewController using Cocoapods. When running unit tests, any view controller that accesses the -slidingViewController property ends up failing because -slidingViewController returns nil. This happens despite the fact that -isKindOfClass and NSStringFromClass both agree that the view controller should be an ECSlidingViewController.

**Comment by backofthecup** [comment]
This still doesn't work. I've tried everything to get this to work:
Added the link_with
````
link_with 'PatientMobile', 'PatientMobileTests'
pod 'AFNetworking', '~> 2.4'
pod 'ECSlidingViewController', '~> 2.0.3'
````

Verified that there are no source files in my test target build phase:
![buildphase](https://cloud.githubusercontent.com/assets/4623150/9803888/33abd308-57ed-11e5-9773-1be9a4254f59.png)

My tests are crashing on this line of code because self.slidingViewController is nil:
````
 [self.navigationController.view addGestureRecognizer:self.slidingViewController.panGesture];

````

**Comment by backofthecup** [comment]
@enriquez 
This looks like a Test/POD issue returning nil for isKindOfClass method. I finally got this working when I changed my Profile to read:
````
target 'PatientMobile' do
    pod 'AFNetworking', '~> 2.4'
    pod 'ECSlidingViewController', '~> 2.0.3'
end

target 'PatientMobileTests'  do
    # this pod is not used by PatientMobileTests, but we need something here to ensure we properly link cocoapods to the PatientMobileTests target
    pod 'OCMock', :head
end

link_with 'PatientMobile', 'PatientMobileTests'


````
